services:
  frontend:
    build: ./front
    image: suguscorp-front:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - corp-network

  backend:
    build: ./back
    image: suguscorp-api:latest
    restart: always
    ports:
    - "4000:4000"
    env_file: ".env"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - LOG_LEVEL=info
      - CORS_ORIGIN=*
    depends_on:
      - corp-db
    volumes:
      - /app/data/users.json
    networks:
      - corp-network

networks:
  corp-network:
    driver: bridge
